language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thepatrvq/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thepatrvq/react-test npm test -- --coverage

after_success:
  - docker build -t thepatrvq/multi-client  ./client
  - docker build -t thepatrvq/multi-nginx   ./nginx
  - docker build -t thepatrvq/multi-server  ./server
  - docker build -t thepatrvq/multi-worker  ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thepatrvq/multi-client
  - docker push thepatrvq/multi-nginx
  - docker push thepatrvq/multi-server
  - docker push thepatrvq/multi-worker
